const allAvatars = [
    "cougar",
    "dribble",
    "flying",
    "green",
    "kobe",
    "lebron",
    "mickey",
    "mjordan",
    "no5",
    "no10",
    "no12",
    "no99",
    "purple",
    "shark",
    "swivel", 
    "african",
    "beard",
    "cleveland",
    "dwayne",
    "red_and_black",
    "seven_stock",
    "thirteen"
  ]
module.exports = allAvatars;
